baseurl = "https://t-tkm.github.io/blog/"
publishDir = "docs"
title = "Takumi Tomita's Blog"
languageCode = "ja"
theme = "pickles"
copyright = "&copy; 2021 Takumi Tomita Powered by Hugo & Pickles."

[params]
  paginate = 10
  twitter = "t_tkm0911"
  facebook = "takumi.tomita.vf"
  linkedin = "takumitomta"
  github = "t-tkm"
  gitlab = "t-tkm"