baseurl = "https://t-tkm.github.io/blog/"
title = "Takumi Tomita's Blog"
languageCode = "ja"
theme = "pickles"
copyright = "&copy; 2022 Takumi Tomita Powered by Hugo & Pickles."
hasCJKLanguage = true # 日本語・中国語・韓国語の単語カウントを有効にする
summaryLength = 320 # サマリーの長さを120単語にする

[params]
  paginate = 10
  twitter = "t_tkm0911"
  facebook = "takumi.tomita.vf"
  linkedin = "takumitomta"
  github = "t-tkm"
  gitlab = "t-tkm"
# Disqus shortname
  author = "Takumi Tomita"
  avatar = "https://www.gravatar.com/avatar/01f65fbc400bf554d948aec41084a9fa"
  bio = "横浜でSWエンジニアやってます。2021, 2022 APN Ambassador (AWS)に選出いただきました。"

[markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4
